name: openaienv
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - ca-certificates=2023.7.22=h8857fd0_0
  - comm=0.1.4=pyhd8ed1ab_0
  - debugpy=1.6.7=py39hcec6c5f_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - ipykernel=6.25.2=pyh1050b4e_0
  - ipython=8.16.1=pyh31c8845_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.2=py39h6e9494a_0
  - libcxx=14.0.6=h9765a3e_0
  - libffi=3.4.4=hecd8cb5_0
  - libsodium=1.0.18=hbcb3906_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=3.1.3=h8a1eda9_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.2.1=py39hecd8cb5_0
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py39hdc70f33_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - python=3.9.17=h5ee71fb_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pyzmq=24.0.1=py39hed8f129_1
  - readline=8.2=hca72f7f_0
  - setuptools=68.0.0=py39hecd8cb5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h6c40b1e_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h5d9f67b_0
  - tornado=6.3.3=py39hdc70f33_1
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - wheel=0.41.2=py39hecd8cb5_0
  - xz=5.4.2=h6c40b1e_0
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - annotated-types==0.5.0
    - anyio==3.7.1
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - babel==2.13.0
    - backoff==2.2.1
    - bcrypt==4.0.1
    - beautifulsoup4==4.12.2
    - bleach==6.1.0
    - certifi==2023.7.22
    - cffi==1.16.0
    - charset-normalizer==3.3.0
    - chroma-hnswlib==0.7.3
    - chromadb==0.4.13
    - click==8.1.7
    - coloredlogs==15.0.1
    - dataclasses-json==0.6.1
    - defusedxml==0.7.1
    - docarray==0.39.0
    - executing==2.0.0
    - fastapi==0.103.2
    - fastjsonschema==2.18.1
    - filelock==3.12.4
    - flatbuffers==23.5.26
    - fqdn==1.5.1
    - frozenlist==1.4.0
    - fsspec==2023.9.2
    - greenlet==2.0.2
    - h11==0.14.0
    - httptools==0.6.0
    - huggingface-hub==0.17.3
    - humanfriendly==10.0
    - idna==3.4
    - importlib-resources==6.1.0
    - isoduration==20.11.0
    - jinja2==3.1.2
    - json5==0.9.14
    - jsonpatch==1.33
    - jsonpointer==2.4
    - jsonschema==4.19.1
    - jsonschema-specifications==2023.7.1
    - jupyter-events==0.7.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.7.3
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.6
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.0
    - langchain==0.0.305
    - langsmith==0.0.41
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - marshmallow==3.20.1
    - mdurl==0.1.2
    - mistune==3.0.2
    - monotonic==1.6
    - mpmath==1.3.0
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.9.2
    - nbformat==5.9.2
    - notebook==7.0.4
    - notebook-shim==0.2.3
    - numexpr==2.8.7
    - numpy==1.26.0
    - onnxruntime==1.16.0
    - openai==0.28.1
    - orjson==3.9.7
    - overrides==7.4.0
    - pandas==2.1.1
    - pandocfilters==1.5.0
    - posthog==3.0.2
    - prometheus-client==0.17.1
    - protobuf==4.24.4
    - pulsar-client==3.3.0
    - pycparser==2.21
    - pydantic==1.10.9
    - pydantic-core==2.10.1
    - pypdf==3.16.2
    - pypika==0.48.9
    - python-dotenv==1.0.0
    - python-json-logger==2.0.7
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - referencing==0.30.2
    - regex==2023.8.8
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.6.0
    - rpds-py==0.10.4
    - send2trash==1.8.2
    - sniffio==1.3.0
    - soupsieve==2.5
    - sqlalchemy==2.0.21
    - stack-data==0.6.3
    - starlette==0.27.0
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.2.3
    - terminado==0.17.1
    - tiktoken==0.5.1
    - tinycss2==1.2.1
    - tokenizers==0.14.1
    - tomli==2.0.1
    - tqdm==4.66.1
    - traitlets==5.10.1
    - typer==0.9.0
    - types-python-dateutil==2.8.19.14
    - types-requests==2.31.0.7
    - typing-inspect==0.9.0
    - tzdata==2023.3
    - uri-template==1.3.0
    - urllib3==2.0.5
    - uvicorn==0.23.2
    - uvloop==0.17.0
    - watchfiles==0.20.0
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.3
    - websockets==11.0.3
    - yarl==1.9.2
prefix: /Users/anwarmo/opt/anaconda3/envs/openaienv
